import type { TaskType } from "./types";

export const tasksInit: TaskType[] = [
  {
    id: "1",
    title: "Сделать обзор проекта",
    description: "Проверить файлы проекта и составить отчет.",
    dueDate: "2025-09-28",
    priority: "high",
    completed: false,
  },
  {
    id: "2",
    title: "Обновить документацию",
    description: "Добавить недостающие разделы и исправить ошибки.",
    dueDate: "2025-10-02",
    priority: "medium",
    completed: false,
  },
  {
    id: "3",
    title: "Встреча с командой",
    description: "Обсудить прогресс и планы на неделю.",
    dueDate: "2025-09-27",
    priority: "low",
    completed: true,
  },
  {
    id: "4",
    title: "Рефакторинг кода",
    description: "Оптимизировать функции и убрать дублирующийся код.",
    dueDate: "2025-10-05",
    priority: "high",
    completed: false,
  },
  {
    id: "5",
    title: "Проверка тестов",
    description: "Запустить все юнит-тесты и исправить ошибки.",
    dueDate: "2025-09-29",
    priority: "medium",
    completed: true,
  },
  {
    id: "6",
    title: "Отправить отчет клиенту",
    description: "Собрать все данные и отправить отчет.",
    dueDate: "2025-09-30",
    priority: "high",
    completed: false,
  },
  {
    id: "7",
    title: "Мелкие исправления UI",
    description: "Подправить стили кнопок и отступы.",
    dueDate: "2025-10-03",
    priority: "none",
    completed: false,
  },
  {
    id: "8",
    title: "Проверка багов",
    description: "Проверить открытые баги и обновить статусы.",
    dueDate: "2025-09-26",
    priority: "high",
    completed: true,
  },
  {
    id: "9",
    title: "Настройка CI/CD",
    description: "Добавить шаги сборки и тестирования.",
    dueDate: "2025-10-06",
    priority: "medium",
    completed: false,
  },
  {
    id: "10",
    title: "Обновление зависимостей",
    description: "Обновить npm-пакеты и проверить совместимость.",
    dueDate: "2025-10-01",
    priority: "low",
    completed: false,
  },
  {
    id: "11",
    title: "Создать презентацию для команды",
    description: "Сделать слайды по итогам месяца.",
    dueDate: "2025-09-30",
    priority: "medium",
    completed: false,
  },
  {
    id: "12",
    title: "Анализ производительности",
    description: "Проверить скорость загрузки страниц и оптимизировать.",
    dueDate: "2025-10-04",
    priority: "high",
    completed: false,
  },
  {
    id: "13",
    title: "Менторство новичков",
    description: "Провести сессию по обучению новых сотрудников.",
    dueDate: "2025-09-29",
    priority: "low",
    completed: true,
  },
  {
    id: "14",
    title: "Планирование спринта",
    description: "Определить задачи на следующий спринт.",
    dueDate: "2025-09-28",
    priority: "high",
    completed: false,
  },
  {
    id: "15",
    title: "Оптимизация базы данных",
    description: "Добавить индексы и проверить запросы.",
    dueDate: "2025-10-05",
    priority: "medium",
    completed: false,
  },
  {
    id: "16",
    title: "Обновление стилей",
    description: "Изменить цветовую схему и шрифты на сайте.",
    dueDate: "2025-10-02",
    priority: "none",
    completed: false,
  },
  {
    id: "17",
    title: "Сбор обратной связи",
    description: "Отправить форму пользователям и собрать отзывы.",
    dueDate: "2025-09-30",
    priority: "low",
    completed: true,
  },
  {
    id: "18",
    title: "Подготовка отчета KPI",
    description: "Собрать ключевые показатели и оформить отчет.",
    dueDate: "2025-10-03",
    priority: "medium",
    completed: false,
  },
  {
    id: "19",
    title: "Обновление логики поиска",
    description: "Добавить фильтры и ускорить поиск по базе данных.",
    dueDate: "2025-10-06",
    priority: "high",
    completed: false,
  },
  {
    id: "20",
    title: "Резервное копирование данных",
    description: "Создать резервные копии всех проектов.",
    dueDate: "2025-10-01",
    priority: "none",
    completed: true,
  },
  {
    id: "21",
    title: "Разработка нового компонента",
    description: "Создать компонент для отображения карточек задач.",
    dueDate: "2025-10-07",
    priority: "medium",
    completed: false,
  },
  {
    id: "22",
    title: "Обновление README",
    description: "Добавить инструкции по запуску проекта.",
    dueDate: "2025-09-29",
    priority: "low",
    completed: true,
  },
  {
    id: "23",
    title: "Тестирование API",
    description: "Проверить все эндпоинты на корректность.",
    dueDate: "2025-10-04",
    priority: "high",
    completed: false,
  },
  {
    id: "24",
    title: "Оптимизация изображений",
    description: "Сжать изображения для ускорения загрузки.",
    dueDate: "2025-10-03",
    priority: "medium",
    completed: true,
  },
  {
    id: "25",
    title: "Добавление логирования",
    description: "Добавить логирование ошибок и событий.",
    dueDate: "2025-10-05",
    priority: "low",
    completed: false,
  },
  {
    id: "26",
    title: "Проверка безопасности",
    description: "Проверить сайт на уязвимости.",
    dueDate: "2025-10-06",
    priority: "high",
    completed: false,
  },
  {
    id: "27",
    title: "Создание скриптов миграции",
    description: "Написать скрипты для обновления базы данных.",
    dueDate: "2025-10-07",
    priority: "medium",
    completed: false,
  },
  {
    id: "28",
    title: "Поддержка пользователей",
    description: "Ответить на запросы пользователей.",
    dueDate: "2025-09-28",
    priority: "low",
    completed: true,
  },
  {
    id: "29",
    title: "Обновление лицензий",
    description: "Проверить и обновить лицензии всех пакетов.",
    dueDate: "2025-10-02",
    priority: "none",
    completed: false,
  },
  {
    id: "30",
    title: "Рефакторинг CSS",
    description: "Убрать дублирующиеся стили и улучшить структуру.",
    dueDate: "2025-10-03",
    priority: "medium",
    completed: false,
  },
  {
    id: "31",
    title: "Создание макетов UI",
    description: "Нарисовать макеты новых страниц.",
    dueDate: "2025-10-01",
    priority: "low",
    completed: true,
  },
  {
    id: "32",
    title: "Добавление тестов компонентов",
    description: "Покрыть тестами новые компоненты.",
    dueDate: "2025-10-05",
    priority: "medium",
    completed: false,
  },
  {
    id: "33",
    title: "Настройка вебхуков",
    description: "Подключить вебхуки для уведомлений.",
    dueDate: "2025-10-06",
    priority: "high",
    completed: false,
  },
  {
    id: "34",
    title: "Обновление иконок",
    description: "Добавить новые иконки и заменить старые.",
    dueDate: "2025-10-02",
    priority: "none",
    completed: false,
  },
  {
    id: "35",
    title: "Оптимизация загрузки скриптов",
    description: "Уменьшить время загрузки JS-файлов.",
    dueDate: "2025-10-04",
    priority: "medium",
    completed: true,
  },
  {
    id: "36",
    title: "Проверка кроссбраузерности",
    description: "Тестировать сайт в разных браузерах.",
    dueDate: "2025-10-03",
    priority: "low",
    completed: false,
  },
  {
    id: "37",
    title: "Документация API",
    description: "Обновить документацию для разработчиков.",
    dueDate: "2025-10-07",
    priority: "medium",
    completed: false,
  },
  {
    id: "38",
    title: "Обновление зависимостей сервера",
    description: "Обновить версии Node и пакетов.",
    dueDate: "2025-10-01",
    priority: "high",
    completed: false,
  },
  {
    id: "39",
    title: "Создание обучающего видео",
    description: "Записать видео по использованию приложения.",
    dueDate: "2025-10-05",
    priority: "low",
    completed: true,
  },
  {
    id: "40",
    title: "Проверка логики авторизации",
    description: "Убедиться, что вход и регистрация работают корректно.",
    dueDate: "2025-10-06",
    priority: "high",
    completed: false,
  },
  {
    id: "41",
    title: "Ревью кода коллег",
    description: "Проверить pull requestы и дать комментарии.",
    dueDate: "2025-09-29",
    priority: "medium",
    completed: true,
  },
  {
    id: "42",
    title: "Добавление анимаций",
    description: "Добавить плавные переходы и эффекты.",
    dueDate: "2025-10-03",
    priority: "none",
    completed: false,
  },
  {
    id: "43",
    title: "Обновление шрифтов",
    description: "Заменить шрифты на новые и согласовать размеры.",
    dueDate: "2025-10-02",
    priority: "low",
    completed: false,
  },
  {
    id: "44",
    title: "Создание тестового окружения",
    description: "Настроить отдельный сервер для тестов.",
    dueDate: "2025-10-04",
    priority: "medium",
    completed: false,
  },
  {
    id: "45",
    title: "Проверка интеграций",
    description: "Убедиться, что все внешние сервисы работают.",
    dueDate: "2025-10-05",
    priority: "high",
    completed: false,
  },
  {
    id: "46",
    title: "Обновление README проекта",
    description: "Добавить инструкции по деплою и сборке.",
    dueDate: "2025-10-01",
    priority: "medium",
    completed: true,
  },
  {
    id: "47",
    title: "Оптимизация запросов к API",
    description: "Сократить количество лишних вызовов.",
    dueDate: "2025-10-06",
    priority: "high",
    completed: false,
  },
  {
    id: "48",
    title: "Проверка мобильной версии",
    description: "Убедиться, что сайт корректно отображается на телефонах.",
    dueDate: "2025-10-03",
    priority: "low",
    completed: true,
  },
  {
    id: "49",
    title: "Реализация темной темы",
    description: "Добавить возможность переключения светлой/темной темы.",
    dueDate: "2025-10-07",
    priority: "medium",
    completed: false,
  },
  {
    id: "50",
    title: "Создание отчета по пользователям",
    description: "Собрать статистику по активности пользователей.",
    dueDate: "2025-10-05",
    priority: "high",
    completed: false,
  },
];
